config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

  resources :users

  resources :topics do
    resources :comments, :controller => 'topic_comments', :only => [:new, :create, :edit, :update, :destroy]

    collection do
      get :about
    end
  end

  namespace :admin do
    root to: "admin#index"

    resources :categories
    resources :users
  end

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    belongs_to :user

    has_many :comments
    has_many :topic_cate_ships
    has_many :categories, :through => :topic_cate_ships

    before_create :get_time_now

    validates_presence_of :title, :content


    def can_manage_by?(user)
      user && ( (self.user == user) || (self.user.admin?) )
    end

    def can_delete_by?(user)
      (self.user == user) || (self.user.admin?)
    end

    def users_unique # unique_users
      users = self.comments.map{ |c| c.user }
      users.unshift(self.user)

      return users.uniq
    end

    protected

    def get_time_now
      self.last_update = Time.now
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :get_topic, :only => [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
    @categories = Category.all

    if params[:cate] == "0"
      # uncategoried
      uncat = Topic.select {|r| r.categories.size == 0}

      # convert array to ActiveRecord::Relation
      # http://stackoverflow.com/questions/17331862/converting-an-array-of-objects-to-activerecordrelation
      @topics = Topic.where(id: uncat.map(&:id))

    elsif params[:cate]
      @topics = Category.find(params[:cate]).topics
    end

    @q = @topics.ransack(params[:q])
    @q.sorts = 'updated_at DESC' if @q.sorts.empty?
    @topics = @q.result.page(params[:page])
  end

  def about
    @user_count = User.count
    @topic_count = Topic.count
    @comment_count = Comment.count
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new( topic_param )

    @topic.user = current_user

    if @topic.save
        flash[:notice] = "Successfully Posted."

        redirect_to topics_path
    else
        render :new
    end
  end

  def show
    @topic.update(:views => @topic.views+1) # extract a model method: @topic.increment_view!
  end

  def edit
  end

  def update
    if @topic.update(topic_param)
        flash[:notice] = "Successfully Edited."

        redirect_to topic_path(@topic)
    else
        render :edit
    end
  end

  def destroy
    if can_delete_by?(current_user)
      @topic.destroy

      flash[:alert] = "Done Deleting!!"
    else
      flash[:alert] = "No Permission to Delete!!"
    end

    redirect_to topics_path
  end

  protected

  def get_topic
    @topic = Topic.find(params[:id])
  end

  def topic_param
    params.require(:topic).permit(:title, :content, :user_id, :category_ids => [])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def merge_topic_filters(params, option)
    filters = params.slice(:sort, :order, :cate)
    filters.merge(option)
  end
end

app/views/topics/_form.html.erb
<% if @topic.errors.any? %>
      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<div class="form-group">
  <%= f.label :title, "Title" %>
  <%= f.text_field :title, :placeholder => "Title of Topic", :class=> "form-control" %>
</div>

<div class="form-group">
  <%= f.label :category_ids, "Category" %> <br />
  <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) %>
</div>

<div class="form-group">
  <%= f.label :content, "內容" %>
  <%= f.text_area :content, :rows => 10, :class=> "form-control" %>
</div>

app/views/topics/about.html.erb
<h1>About AC Forum</h1>

<p>Registered Users: <%= @user_count %></p>
<p>Topics: <%= @topic_count %></p>
<p>Comments: <%= @comment_count %></p>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<%= form_for @topic do |f| %>

  <%= render "form", :f => f %>

  <div class="form-group">
    <%= f.submit "送出", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Topics</h1>
  </div>
  <div class="col-md-6 new_topic">
    <%= link_to new_topic_path, :class => "btn btn-primary pull-right" do %>
      <span class="glyphicon glyphicon-plus"></span> New Topic
    <% end %>
  </div>
</div>

<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

<div class="row">
  <ul class="nav nav-tabs">
    <li role="presentation" class="<%= (params[:cate])? "": "active" %>"><%= link_to "All", topics_path %></li>

    <% @categories.each do |cat| %>

      <li role="presentation" class="<%= (params[:cate] == cat.id.to_s)? "active": "" %>"><%= link_to cat.name, topics_path( :cate => cat.id ) %></li>
    <% end %>

    <li role="presentation" class="<%= (params[:cate] == "0")? "active": "" %>"><%= link_to "Uncategoried", topics_path( :cate => 0 ) %></li>

  </ul>

</div>

<table class="table table-striped table-hover">
  <tr>
    <th></th>
    <th>Topic</th>
    <th>Category</th>
    <th>Users</th>
    <th><%= sort_link @q, :comments_count, "Replies", :default_order => :desc %></th>
    <th><%= sort_link @q, :views, "Views", :default_order => :desc %></th>
    <th><%= sort_link @q, :updated_at, "Updated", :default_order => :desc %></th>
  </tr>

  <% @topics.each do |t| %>
    <tr>
      <td><%= t.id %></td>
      <td class="col-md-6"><%= link_to t.title, topic_path(t) %></td>
      <td>
        <% t.categories.each do |cat| %>
          <%= link_to topics_path( :cate => cat.id ) do %>
            <span class="badge"><%= cat.name %></span>
          <% end %>
        <% end %>
      </td>
      <td>
        <% t.users_unique.each do |user| %>
          <%= link_to user.username, user_path(user.id) %>
        <% end %>
      </td>
      <td><%= t.comments.size %></td>
      <td><%= t.views %></td>
      <td><%= t.updated_at.to_s(:short) %></td>
    </tr>
  <% end %>
</table>

<%= paginate @topics %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= form_for @topic do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <div class="form-group">
    <%= f.submit "送出", :class => "btn btn-primary" %>
  </div>

<% end %>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

<div class="categories">
  <% @topic.categories.each do |c| %>
    <span class="badge"><%= c.name %></span>
  <% end %>
</div>

<hr>
<ul class="media-list">
  <li class="media">
    <div class="media-left">
      <%= link_to user_path(@topic.user) do %>
        <%= avatar_image(@topic.user) %>
      <% end %>

    </div>
    <div class="media-body">
    	<div class="topic_header">
				<%= link_to @topic.user.username, user_path(@topic.user) %> posted on <%= @topic.created_at.to_s(:short) %>

				<% if current_user %>
					<%= link_to new_topic_comment_path(@topic), :class => "btn btn-primary pull-right" do %>
            <span class="glyphicon glyphicon-plus"></span> Reply
          <% end %>
        <% end %>

				<% if @topic.can_manage_by?(current_user) %>
				  <%= link_to "Edit", edit_topic_path(@topic), :class => "btn btn-default pull-right" %>

					<%= link_to "Delete", topic_path(@topic), :method => :delete, :data => { :confirm => "Are you sure to delete?" }, :class => "btn btn-danger pull-right" %>
				<% end %>

    	</div>
			<p><%= simple_format @topic.content %></p>
    </div>
  </li>
</ul>

<% if @topic.comments %>
	<h3>Comments</h3>
	<ul class="media-list">

		<% @topic.comments.each do |comment| %>

		  <li class="media">
		    <div class="media-left">
          <%= link_to user_path(comment.user) do %>
            <%= avatar_image(comment.user) %>
          <% end %>
		    </div>
		    <div class="media-body">
		    	<div class="comment_header">
						<%= link_to comment.user.username, user_path(comment.user) %> replied on <%= comment.created_at.to_s(:short) %>

						<% if comment.can_manage_by?(current_user) %>
							<%= link_to "Edit", edit_topic_comment_path(@topic, comment), :class => "btn btn-default btn-xs pull-right" %>

							<%= link_to "Delete", topic_comment_path(@topic, comment), :method => :delete, :data => { :confirm => "Are you sure to delete?" }, :class => "btn btn-danger btn-xs pull-right" %>

						<% end %>

		    	</div>
		      <p><%= simple_format comment.content %></p>
		    </div>
		  </li>
	  <% end %>
	</ul>
<% end %>