config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: 'users/registrations' }

  resources :users

  resources :topics do
    resources :comments, :controller => 'topic_comments', :only => [:new, :create, :edit, :update, :destroy]

    collection do
      get :about
    end
  end

  namespace :admin do
    root to: "admin#index"

    resources :categories
    resources :users
  end

  root 'topics#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

    has_many :topic_cate_ships
    has_many :topics, :through => :topic_cate_ships

    validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :topic, :counter_cache => true, :touch => true

    validates_presence_of :content

    def can_manage_by?(user)
      user && ( (self.user == user) || (self.user.admin?) )
    end

    def can_delete_by?(user)
      (self.user == user) || (self.user.admin?)
    end

end

app/models/topic.rb
class Topic < ActiveRecord::Base
    belongs_to :user

    has_many :comments
    has_many :topic_cate_ships
    has_many :categories, :through => :topic_cate_ships

    before_create :get_time_now

    validates_presence_of :title, :content


    def can_manage_by?(user)
      user && ( (self.user == user) || (self.user.admin?) )
    end

    def can_delete_by?(user)
      (self.user == user) || (self.user.admin?)
    end

    def users_unique # unique_users
      users = self.comments.map{ |c| c.user }
      users.unshift(self.user)

      return users.uniq
    end

    protected

    def get_time_now
      self.last_update = Time.now
    end
end

app/models/topic_cate_ship.rb
class TopicCateShip < ActiveRecord::Base

    belongs_to :topic
    belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    validates_presence_of :role

    has_many :topics
    has_many :comments

    def admin?
      self.role == "admin"
    end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
    @categories = Category.all
    @new_category = Category.new

    @users = User.all
  end

  protected

  def check_admin
    unless current_user.admin?
      flash[:alert] = "Not Admin!"
      redirect_to root_path
      return
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :get_user

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_root_path
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:bio, :role)
  end

  def get_user
    @user = User.find(params[:id])
  end

  def check_admin
    unless current_user.admin?
      flash[:alert] = "Not Admin!"
      redirect_to root_path
      return
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :bio) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :bio) }
    end
end

app/controllers/topic_comments_controller.rb
class TopicCommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :get_topic

  def new
    @comment = @topic.comments.build
  end

  def create
    @comment = @topic.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Replied."

      redirect_to topic_path(@topic)
    else
      render :new
    end
  end

  def edit
    @comment = @topic.comments.find(params[:id])
  end

  def update
    @comment = @topic.comments.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = "Comment Edited."

      redirect_to topic_path(@topic)
    else
      render :edit
    end
  end

  def destroy
    @comment = @topic.comments.find(params[:id])

    if @comment.can_delete_by(current_user)
      @comment.destroy

      flash[:alert] = "Comment Deleted."
    else
      flash[:alert] = "No Permission to Delete!!"
    end

    redirect_to topic_path(@topic)
  end

  protected

  def get_topic
    @topic = Topic.find( params[:topic_id] )
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :get_topic, :only => [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
    @categories = Category.all

    if params[:cate] == "0"
      # uncategoried
      uncat = Topic.select {|r| r.categories.size == 0}

      # convert array to ActiveRecord::Relation
      # http://stackoverflow.com/questions/17331862/converting-an-array-of-objects-to-activerecordrelation
      @topics = Topic.where(id: uncat.map(&:id))

    elsif params[:cate]
      @topics = Category.find(params[:cate]).topics
    end

    @q = @topics.ransack(params[:q])
    @q.sorts = 'updated_at DESC' if @q.sorts.empty?
    @topics = @q.result.page(params[:page])
  end

  def about
    @user_count = User.count
    @topic_count = Topic.count
    @comment_count = Comment.count
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new( topic_param )

    @topic.user = current_user

    if @topic.save
        flash[:notice] = "Successfully Posted."

        redirect_to topics_path
    else
        render :new
    end
  end

  def show
    @topic.update(:views => @topic.views+1) # extract a model method: @topic.increment_view!
  end

  def edit
  end

  def update
    if @topic.update(topic_param)
        flash[:notice] = "Successfully Edited."

        redirect_to topic_path(@topic)
    else
        render :edit
    end
  end

  def destroy
    if can_delete_by?(current_user)
      @topic.destroy

      flash[:alert] = "Done Deleting!!"
    else
      flash[:alert] = "No Permission to Delete!!"
    end

    redirect_to topics_path
  end

  protected

  def get_topic
    @topic = Topic.find(params[:id])
  end

  def topic_param
    params.require(:topic).permit(:title, :content, :user_id, :category_ids => [])
  end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topic_comments_helper.rb
module TopicCommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  def merge_topic_filters(params, option)
    filters = params.slice(:sort, :order, :cate)
    filters.merge(option)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_image(user)
    hash = Digest::MD5.hexdigest(user.email)
    image_tag("http://www.gravatar.com/avatar/#{hash}", :class => "media-object gravatar", :alt => user.username)
  end

end

app/views/admin/admin/index.html.erb
<script>
  $(function () {
    $(".cate_name").hide();

    $(".edit_cat").click(function (event) {
      event.preventDefault();

      var cid = $(this).data("cid");
      $(".cat"+cid).toggle();
    });
  });
</script>

<h1>Admin Backstage!</h1>
<hr>

<h2>Categories Management</h2>

<%= form_for [:admin, @new_category] do |f| %>

  <% if @new_category.errors.any? %>
    <ul>
    <% @new_category.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="form-group form-inline">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, :class=> "form-control" %>
    <%= f.submit "New Category", :class => "btn btn-primary" %>
  </div>

  <div class="form-group">
  </div>

<% end %>

<table class="table table-bordered">
  <% @categories.each do |c| %>
    <tr>
      <td>
        <%= c.name %>
        <div class="cate_name cat<%= c.id %>">
          <%= form_for [:admin, c] do |f| %>
            <div class="form-group form-inline">
              <%= f.text_field :name, :class=> "form-control" %>

              <%= f.submit "Rename", :class => "btn btn-primary" %>
            </div>
          <% end %>
        </div>
        <a href="#" class="edit_cat" data-cid="<%= c.id %>">Edit</a>
      </td>
      <td><%= c.topics.size %></td>
      <td>
        <% if c.topics.size == 0 %>
          <%= link_to "Delete", admin_category_path(c), :method => "delete", :class => "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<h2>User Management</h2>
<table class="table table-bordered">
  <% @users.each do |p| %>
    <tr>
      <td><%= p.username %></td>
      <td><%= p.role %></td>
      <td><%= link_to "Edit", edit_admin_user_path(p), :class => "btn btn-primary" %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.3";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">AC Forum</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
                <% if current_user.admin? %>
                    <li><%= link_to "Backstage", admin_root_path %></li>
                <% end %>
                <li><%= link_to "About", about_topics_path %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%= current_user.username %><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                        </li>
                        <li>
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        </li>
                    </ul>
                </li>

            <% else %>
                <li>
                    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                </li>
                <li>
                    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                </li>
            <% end %>


        </ul>
    </div><!-- /.navbar-collapse -->
</nav>

<div class="wrapper">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
</div>

</body>
</html>